### ISSUE TITLE
resposive

### ISSUE THREAD

**Issue by faqsun** [sendz/dirakit-project#1]
profile.html belom responsive

**Comment by faqsun** [comment]
project-overview.html
belom responsive
kasih sourcecode editor
menu belom ikut turun

**Comment by faqsun** [comment]
challenge-3.html

alat dan bahan haruse ada add new hardware, add new software

**Comment by faqsun** [comment]
challenge-3.html

belom bisa tambah langkah

**Comment by faqsun** [comment]
challenge-1 sampe challenge-4 

menu dibawah ada kembali simpan lanjutkan

**Comment by sendz** [comment]
Create separate ticket for any single issue, please.
