### ISSUE TITLE
loading halaman utama

### ISSUE THREAD

**Issue by faqsun** [sendz/dirakit-project#12]
loading halaman utama kayak google image muncul 2 baris, abis itu kalo user sekrol kebawah baru dia loading lagi 2 baris segitu terus sampe abis
# iki kanggo index.html dan halaman2 yang menampilkan project (aku lali)

**Comment by sendz** [comment]
@faqsun infinite loading gitu ya?

**Comment by faqsun** [comment]
yes

**Comment by sendz** [comment]
ini aku bikin contoh di index aja ya... 30a4d59
