### ISSUE TITLE
footer kebesaran

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#16]
Cek website yg sekarang, kira2 segitu

**Comment by sendz** [comment]
@fauzan-ngantuk lebih detail dong, footer di layout mana. mobile, tablet, PC. kalau bisa ada screenshot perbandingan juga. @faqsun

**Comment by sendz** [comment]
kalau buka di mobile atau tablet atau display yang HD bakal keliatan lebih gede, karena web yang sekarang gak diset viewport scale nya.

**Comment by nauzaf** [comment]
Mungkin kalau bisa, footer yg di versi pc ukurannya kayak di website yg sekarang, kalo versi mobile nya udah pas menurutku

**Comment by sendz** [comment]
Done
