### ISSUE TITLE
Title dikasih favicon

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#17]
kasih logo dirakit di title ya , ini logonya 
<img width="186" alt="ico" src="https://cloud.githubusercontent.com/assets/23164248/19921171/45848d7e-a10f-11e6-98cf-6c677eadb5e9.png">

**Comment by sendz** [comment]
@fauzan-ngantuk title bar di browser ya? boleh minta yang .ico nya juga?

**Comment by sendz** [comment]
86e4c6a and 1c7c71e
