### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#18]
Ganti gambar nya pake ini yoo 
![1](https://cloud.githubusercontent.com/assets/23164248/19921295/ded441b8-a10f-11e6-8939-569a99641e42.jpg)

**Comment by nauzaf** [comment]
nanti taglinnya kayak gini juga
![desktop verse](https://cloud.githubusercontent.com/assets/23164248/19921368/33cd452a-a110-11e6-9382-619c85cd4b36.jpg)

**Comment by nauzaf** [comment]
Button lebih lanjut kalu dihover jadi biru
![desktop verse hover](https://cloud.githubusercontent.com/assets/23164248/19921448/8c0164c4-a110-11e6-9773-4aea775c8bf4.jpg)

**Comment by nauzaf** [comment]
versi mobile
![mobile verse](https://cloud.githubusercontent.com/assets/23164248/19921510/c11e827c-a110-11e6-9bc7-1e8f8f1c46ba.jpg)

**Comment by sendz** [comment]
@fauzan-ngantuk 

> Button lebih lanjut kalu dihover jadi biru

Bikin issue baru buoss...

**Comment by sendz** [comment]
Done 2cc6b03
