### ISSUE TITLE
Tab diganti

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#19]
tab nya dibuat kayak gini bisa ndak ?
yang versi pc nya gini 
![desktop tab](https://cloud.githubusercontent.com/assets/23164248/19921843/4c9d2ea6-a112-11e6-92e9-339e2c40add4.jpg)
yang versi mobile nya gini
![mobile verse](https://cloud.githubusercontent.com/assets/23164248/19921848/5961efdc-a112-11e6-80e1-e628dfea0954.jpg)

**Comment by sendz** [comment]
@fauzan-ngantuk done here 8d3c81e
please verify and close this issue

**Comment by sendz** [comment]
Confirmed for appearance.
