### ISSUE TITLE
Flat Card

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#20]
Desain Card Project dibuat flat aja , sc nya gini 
![project](https://cloud.githubusercontent.com/assets/23164248/19921915/bcdc2460-a112-11e6-95ec-d87964d11e1f.jpg)

**Comment by nauzaf** [comment]
![flat card](https://cloud.githubusercontent.com/assets/23164248/19922041/636dc752-a113-11e6-9b29-1de25248cc3a.jpg)

**Comment by sendz** [comment]
Done 21b4083

Please verify and close this issue @fauzan-ngantuk
