### ISSUE TITLE
Project Page

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#22]
desain buat project page
![project](https://cloud.githubusercontent.com/assets/23164248/19922266/742e7bc6-a114-11e6-8e59-eecc84ac073f.jpg)

**Comment by nauzaf** [comment]
ini buat tagline 
![2](https://cloud.githubusercontent.com/assets/23164248/19922325/bca14bcc-a114-11e6-8d91-d52aa2c853e0.jpg)

**Comment by sendz** [comment]
Done 07855ba
