### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#23]
Desain Plaform + card nya kayak gini 
![platform](https://cloud.githubusercontent.com/assets/23164248/19922464/564ffd7c-a115-11e6-8105-99ff9f1d6eae.jpg)

**Comment by nauzaf** [comment]
versi mobile
![mobile verse](https://cloud.githubusercontent.com/assets/23164248/19922487/6cf83a76-a115-11e6-8135-21f1ffbd2dda.jpg)

**Comment by nauzaf** [comment]
buat tagline
![3](https://cloud.githubusercontent.com/assets/23164248/19922520/8df1f91a-a115-11e6-8da8-afa98e954e62.jpg)

**Comment by sendz** [comment]
Done c41e701 and b7ccfac
