### ISSUE TITLE
Challenge Page

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#25]
Tagline Challenge ganti ini sama kayak di project page
![web verse](https://cloud.githubusercontent.com/assets/23164248/19923303/43abc210-a119-11e6-9a41-b3e096642fa3.jpg)

**Comment by nauzaf** [comment]
versi mobile
![chalenge mobile verse](https://cloud.githubusercontent.com/assets/23164248/19923333/70121930-a119-11e6-9411-ab6704926653.jpg)

**Comment by sendz** [comment]
@fauzan-ngantuk emang yang sekarang gimana?

**Comment by nauzaf** [comment]
Yang sekarang masih pake gambar yg ada label shutterstock nya to haha

**Comment by sendz** [comment]
@fauzan-ngantuk gambarnya dong upload sini

**Comment by sendz** [comment]
Done 78850a2
