### ISSUE TITLE
Height Project jika size gambar beda

### ISSUE THREAD

**Issue by iqbalprabu** [sendz/dirakit-project#26]
ukuran height project beda2 jika ukuran image nya beda2 juga.

![image](https://cloud.githubusercontent.com/assets/16696807/19956543/67808c82-a1c0-11e6-9e6d-89a9dd1f10ec.png)

**Comment by sendz** [comment]
@iqbalprabu @faqsun give me a number for height, 154px?

**Comment by iqbalprabu** [comment]
ya itu cukup mas...

**Comment by faqsun** [comment]
Aan pls gv number, 

thanks

**Comment by sendz** [comment]
@faqsun 

> 188px

jare Aan sih

**Comment by sendz** [comment]
Done e8f02b5
