### ISSUE TITLE
Change Font to Roboto

### ISSUE THREAD

**Issue by sendz** [sendz/dirakit-project#27]
Please populate all element which will use Roboto
@fauzan-ngantuk

**Comment by sendz** [comment]
@fauzan-ngantuk please reply

**Comment by nauzaf** [comment]
aku suruh ngapain ?

**Comment by sendz** [comment]
@fauzan-ngantuk dibaca tuh paling atas, katanya mau pake roboto

**Comment by sendz** [comment]
padahal kamu yang minta beberapa pake roboto an...

**Comment by nauzaf** [comment]
"lebih lanjut" di uppercase mas .. kalau udah diclose aja hehe  ![image](https://cloud.githubusercontent.com/assets/23164248/20244163/9c628866-a9a8-11e6-9eb3-cadad9fa9012.png)

**Comment by nauzaf** [comment]
@sendz

**Comment by sendz** [comment]
Done 04f1df2
