### ISSUE TITLE
Project Page Versi Mobile

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#30]
Project page dibuat kayak gini ada opsi lain buat minimize total project, filter sama buat project (kayak yang kita bahas tadi sore haha)
![project mobile verse](https://cloud.githubusercontent.com/assets/23164248/19969268/965bd8be-a20a-11e6-9679-8f07bd78226e.jpg)

**Comment by sendz** [comment]
Done here df06fe9
