### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#31]
Versi PC
![pc verse](https://cloud.githubusercontent.com/assets/23164248/19969696/18e830b0-a20c-11e6-82e8-112673307db2.jpg)
Versi Mobile
![mobile v3](https://cloud.githubusercontent.com/assets/23164248/19969810/891cf514-a20c-11e6-8443-fb9850230291.jpg)

**Comment by sendz** [comment]
done 64995c3
