### ISSUE TITLE
Challenge-3

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#32]
nanti desainnya form nya seperti ini
![challenge](https://cloud.githubusercontent.com/assets/23164248/19990858/90b0eb1c-a263-11e6-8a90-426a96b4f2cc.jpg)

**Comment by sendz** [comment]
ini desain form apa @fauzan-ngantuk ?

**Comment by nauzaf** [comment]
itu page form alat & bahan (challenge-3.html)

**Comment by nauzaf** [comment]
@sendz
