### ISSUE TITLE
Challenge-4

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#35]
Desain page nya dibuat gini bisa gak yah ?
![langkah-langkah](https://cloud.githubusercontent.com/assets/23164248/19991097/541aa1f0-a265-11e6-8a13-ed9132c75ddd.jpg)
Buat yang versi mobile dipending dulu hehe

**Comment by sendz** [comment]
@fauzan-ngantuk will not fix, conflict with #36
