### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#36]
Untuk Text Editornya nanti gini 
![editor](https://cloud.githubusercontent.com/assets/23164248/19991123/8c7e32d2-a265-11e6-8923-d96ff666ed46.jpg)

**Comment by sendz** [comment]
@fauzan-ngantuk desainnya ganti jadi gini apa tetep pake yang sekarang?

**Comment by nauzaf** [comment]
diganti kayak gitu , soalnya nanti text editornya gak bisa import gambar, import gambar harus lewat atasnya itu.

**Comment by nauzaf** [comment]
@sendz

**Comment by sendz** [comment]
done f41dcc4
