### ISSUE TITLE
Penyesuaian footer

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#37]
Beberapa page footer nya kalau di resolusi layar yg gede jadinya kayak gini
![capture2](https://cloud.githubusercontent.com/assets/23164248/19991286/b6f4766a-a266-11e6-8edf-3cdfa68bf2a1.PNG)
banyak sisa di bawah. bisa ndak nanti footer yg kayak gitu menyesuaikan hehe

**Comment by sendz** [comment]
@fauzan-ngantuk please test on your desktop as well, and close this issue if all good.

**Comment by nauzaf** [comment]
sudah
