### ISSUE TITLE
Form Icon

### ISSUE THREAD

**Issue by nauzaf** [sendz/dirakit-project#43]
icon form yang ini 
![capture](https://cloud.githubusercontent.com/assets/23164248/20134642/c552ca7c-a69e-11e6-95b4-978b8ba88de8.PNG)
diganti ini
![ico](https://cloud.githubusercontent.com/assets/23164248/20134650/cbe7c7b6-a69e-11e6-8239-a4da44cd4ae4.png)

**Comment by sendz** [comment]
@fauzan-ngantuk itu image sih, tadinya diganti icon karena memang pengen ngurangi load image yang berlebih. Cc @faqsun

**Comment by nauzaf** [comment]
Pake yg ixon ajaa gk papa, brati gak usah diganti

**Comment by nauzaf** [comment]
@sendz
